- name: Update APT
  hosts: smt
  tasks:
    - name: Update installed packages
      apt:
        name: '*'
        state: latest
        update_cache: yes
        only_upgrade: yes
      register: apt_update_status

    - name: Remove unused packages
      apt:
        autoremove: yes