version: '3'

services:
  uptimekuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data

networks:
  default:
    name: mainNetwork
    external: true

