- name: Enable Dell SMM 
  hosts: smt
  tasks:
    - name: "Add i8k to /etc/modules"
      lineinfile:
        path: "/etc/modules"
        line: 'i8k'
      register: modules-i8k
    
    - name: "Add i8k options"
      lineinfile:
        path: "/etc/modprobe.d/i8k.conf"
        line: 'options i8k force=1'
        create: true
      register: options-i8k