- name: Create a Fedora Cloud template
  hosts: smt
  tasks:
    - name: "Download Fedora Cloud Image"
      shell: >
        wget -O /root/FedoraCloud39.qcow2 https://download.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-39-1.5.x86_64.qcow2

    - name: "Create the VM"
      shell: >
        qm create {{ template_id }} --name "Fedora39-Cloud" --memory 2048 --cores 2 --net0 virtio,bridge=vmbr0

    - name: "Configure the VM"
      shell: |
        qm set {{ template_id }} --description "Fedora 39 Cloud image template | Cloud init ready"
        qm importdisk {{ template_id }} /root/FedoraCloud39.qcow2 local-lvm
        qm set {{ template_id }} --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-{{ template_id }}-disk-0
        qm set {{ template_id }} --boot c --bootdisk scsi0
        qm set {{ template_id }} --ide0 local-lvm:cloudinit
        qm set {{ template_id }} --agent enabled=1
        qm set {{ template_id }} --onboot 1
        qm set {{ template_id }} --ostype l26
        qm set {{ template_id }} --ipconfig0=dhcp
        qm set {{ template_id }} --ciuser "jndvasco"
        qm set {{ template_id }} --sshkey /root/.ssh/authorized_keys
        qm set {{ template_id }} --tags "Fedora"

    - name: "Convert VM to template"
      shell: >
        qm template {{ template_id }}



