- name: Enable iommu and load the modules
  hosts: smt
  tasks:
  - name: Enable iommu in grub
    lineinfile:
      path: "/etc/default/grub"
      backrefs: true
      regexp: '^#?(GRUB_CMDLINE_LINUX_DEFAULT=.*)quiet"$'
      line: '\1quiet intel_iommu=on iommu=pt"'
    register: iommuGrub

  - name: Update Grub
    shell: |
      update-grub
    register: updateGrub

  - name: Load modules at boot
    lineinfile:
      path: "/etc/modules"
      line: '{{ item }}'
    with_items:
      - vfio
      - vfio_iommu_type1
      - vfio_pci
    register: loadModules

  - name: Allow unsafe interrupts
    lineinfile:
      path: "/etc/modprobe.d/iommu_unsafe_interrupts.conf"
      create: true
      line: 'options vfio_iommu_type1 allow_unsafe_interrupts=1'
    register: unsafeInterrupts

  - name: Refresh initramfs
    shell: |
      update-initramfs -u -k all
    register: initramfs
